d @CMAKE_INSTALL_FULL_LOCALSTATEDIR@/cache/icinga2 0750 @ICINGA2_USER@ @ICINGA2_GROUP@
d @ICINGA2_RUNDIR@/icinga2 0755 @ICINGA2_USER@ @ICINGA2_COMMAND_GROUP@
d @ICINGA2_RUNDIR@/icinga2/cmd 2750 @ICINGA2_USER@ @ICINGA2_COMMAND_GROUP@
d ICINGA2_ERROR_LOG=@CMAKE_INSTALL_FULL_LOCALSTATEDIR@/log/icinga2 0750 @ICINGA2_USER@ @ICINGA2_COMMAND_GROUP@
